# Makefile for biconnectivity homework
# @author James Edwards
# @revision $revision$
# @ID $Id: Makefile 8267 2009-04-24 05:17:51Z keceli $
#
#===========================================================================
#

MAKE_FILE ?= /opt/xmt/class/make/biconnectivity.mk

include $(MAKE_FILE)
